### ISSUE TITLE
[cursor] Node.removeChild: Argument 1 does not implement interface Node.

### ISSUE THREAD

**Issue by caugner** [katspaugh/wavesurfer.js#2460]
Since upgrading to Wavesurfer.js, our Sentry is catching the following exceptions when our app calls `wavesurfer.destroy()`:

```
TypeError: Node.removeChild: Argument 1 does not implement interface Node.
  at destroy(./node_modules/wavesurfer.js/dist/plugin/wavesurfer.cursor.js:250:30)
  at destroyPlugin(./node_modules/wavesurfer.js/dist/wavesurfer.js:4316:18)
  at forEach(./node_modules/wavesurfer.js/dist/wavesurfer.js:4334:23)
  at destroyAllPlugins(./node_modules/wavesurfer.js/dist/wavesurfer.js:4333:47)
  at destroy(./node_modules/wavesurfer.js/dist/wavesurfer.js:5541:12)
```

and

```
TypeError: this.cursor is null
  at destroy(./node_modules/wavesurfer.js/dist/plugin/wavesurfer.cursor.js:250:7)
  at destroyPlugin(./node_modules/wavesurfer.js/dist/wavesurfer.js:4316:18)
  at forEach(./node_modules/wavesurfer.js/dist/wavesurfer.js:4334:23)
  at destroyAllPlugins(./node_modules/wavesurfer.js/dist/wavesurfer.js:4333:47)
  at destroy(./node_modules/wavesurfer.js/dist/wavesurfer.js:5541:12)
```

👇 
https://github.com/katspaugh/wavesurfer.js/blob/46d423b882d503cafd4d2498a230ff20ce39fe19/src/plugin/cursor/index.js#L242

```
TypeError: can't access property "getBoundingClientRect", o.displayTime is null
  at apply(./node_modules/wavesurfer.js/dist/plugin/wavesurfer.cursor.js:122:18)
  at o(./node_modules/@sentry/browser/esm/helpers.js:73:23)
```

👇 
https://github.com/katspaugh/wavesurfer.js/blob/bff81af86e581412ed2b506b9fbeb706b605d663/src/plugin/cursor/index.js#L93

**Comment by caugner** [comment]
Probably caused by changes introduced in #2357.

We're creating the `WaveSurfer` instance as follows:

```js
    const state = reactive({
      timelineId: '_' + uuidv4(),
      waveId: '_' + uuidv4(),
      wavesurfer: null as WaveSurfer | null,
    })

    state.wavesurfer = WaveSurfer.create({
        container: '#' + state.waveId,
        autoCenter: true,
        mediaControls: true,
        normalize: true,
        removeMediaElementOnDestroy: false,
        backend: 'MediaElement',
        progressColor: 'purple',
        cursorColor: 'navy',
        plugins: [
          WaveSurferCursor.create({}),
          WaveSurferMinimap.create({}),
          WaveSurferRegions.create({
            regions: props.regions,
          }),
          WaveSurferTimeline.create({
            container: '#' + state.timelineId,
          }),
        ],
      })
```

**Comment by caugner** [comment]
I verified that downgrading to 5.2.0 fixed the issue.

**Comment by thijstriemstra** [comment]
Any idea what's going on here @Ivaka?
